# DO NOT EDIT THIS FILE - MAKE A COPY CALLED 'azint_config.py' AND EDIT THAT ONE!

# path to poni file [string]
poni_file = f'/data/visitors/danmax/PROPOSAL/VISIT/process/myPoni.poni'

# path to mask file in npy format [string]
mask_file = f'/data/visitors/danmax/PROPOSAL/VISIT/process/myMask.npy'

# settings used in the integration
user_config = {'poni': poni_file, # do not change this line
          'mask': mask_file, # do not change this line
          'correction_image' : None, # Correction applied to data before integration
          'radial_bins': 3000, # number of radial bins [int]
          'azimuth_bins': None, # number of azimuthal bins (or list specifying the azimuthal bins)
          'n_splitting': 21, # pixel splitting - number of subdivisions [int[]]
          'error_model': None, # Error model: use 'None' or 'poisson' [str]
          'polarization_factor': 0.999997, # Polarization factor - use 0.999997 [float]
          'unit': 'q' # Radial unit: use either 'q' or '2th' [str]
          }

# Specification of scans to be integrated [list of int]
scans = range(firstScan, lastScan+1) # Specified as a range, remeber to end with lastScan+1
#scans = [scan1, scan2, scanN] # Manually specified list

# DO NOT EDIT THIS FILE - MAKE A COPY CALLED 'azint_config.py' AND EDIT THAT ONE!
